# Generated by Django 3.2.13 on 2023-12-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20231207_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank='', default='https://github.com/crystallinexxii', max_length=200),
            preserve_default=False,
        ),
    ]
