# Generated by Django 3.2.13 on 2023-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_branch',
            field=models.CharField(default='master', max_length=10),
        ),
    ]
